import './globals.css';
import { Nunito } from 'next/font/google';

import { Navbar } from './components/navbar';
import { ClientOnly } from './components';
import { ToasterProvider } from './providers';
import { LoginModal, RegisterModal } from './components/modals';
import { getCurrentUser } from './actions';

const font = Nunito({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang='en'>
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <LoginModal />
          <RegisterModal />
          <Navbar currentUser={currentUser} />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
